name: appstitch_stripe
description: Stripe Integrations for Appstitch.
version: 2.0.1-nullsafety.1
homepage: https://appstitch.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  appstitch_core: ^2.0.0-nullsafety.1
  json_annotation: ^4.0.0
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.0
  json_serializable: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.appstitch.stripe
        pluginClass: AppstitchStripePlugin
      ios:
        pluginClass: AppstitchStripePlugin
