name: appstitch_stripe
description: Stripe Integrations using Appstitch.
version: 1.0.4
homepage: https://appstitch.dev

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  appstitch_core: ^1.0.0
  json_annotation: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.0
  json_serializable: ^3.5.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.appstitch.stripe
        pluginClass: AppstitchStripePlugin
      ios:
        pluginClass: AppstitchStripePlugin
